### YamlMime:ManagedReference
items:
- uid: Foundry.ControllerConfig.DeviceOffset
  commentId: T:Foundry.ControllerConfig.DeviceOffset
  id: ControllerConfig.DeviceOffset
  parent: Foundry
  children:
  - Foundry.ControllerConfig.DeviceOffset.controllerOffsets
  - Foundry.ControllerConfig.DeviceOffset.headOffset
  - Foundry.ControllerConfig.DeviceOffset.name
  langs:
  - csharp
  - vb
  name: ControllerConfig.DeviceOffset
  nameWithType: ControllerConfig.DeviceOffset
  fullName: Foundry.ControllerConfig.DeviceOffset
  type: Class
  source:
    remote:
      path: package/Player/Scripts/ControllerConfig.cs
      branch: main
      repo: https://github.com/FoundryXR/FoundryCore
    id: DeviceOffset
    path: ../Player/Scripts/ControllerConfig.cs
    startLine: 20
  assemblies:
  - Foundry.Core
  namespace: Foundry
  syntax:
    content: >-
      [Serializable]

      public class ControllerConfig.DeviceOffset
    content.vb: >-
      <Serializable>

      Public Class ControllerConfig.DeviceOffset
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: Foundry.ControllerConfig.DeviceOffset.name
  commentId: F:Foundry.ControllerConfig.DeviceOffset.name
  id: name
  parent: Foundry.ControllerConfig.DeviceOffset
  langs:
  - csharp
  - vb
  name: name
  nameWithType: ControllerConfig.DeviceOffset.name
  fullName: Foundry.ControllerConfig.DeviceOffset.name
  type: Field
  source:
    remote:
      path: package/Player/Scripts/ControllerConfig.cs
      branch: main
      repo: https://github.com/FoundryXR/FoundryCore
    id: name
    path: ../Player/Scripts/ControllerConfig.cs
    startLine: 23
  assemblies:
  - Foundry.Core
  namespace: Foundry
  syntax:
    content: public string name
    return:
      type: System.String
    content.vb: Public name As String
- uid: Foundry.ControllerConfig.DeviceOffset.headOffset
  commentId: F:Foundry.ControllerConfig.DeviceOffset.headOffset
  id: headOffset
  parent: Foundry.ControllerConfig.DeviceOffset
  langs:
  - csharp
  - vb
  name: headOffset
  nameWithType: ControllerConfig.DeviceOffset.headOffset
  fullName: Foundry.ControllerConfig.DeviceOffset.headOffset
  type: Field
  source:
    remote:
      path: package/Player/Scripts/ControllerConfig.cs
      branch: main
      repo: https://github.com/FoundryXR/FoundryCore
    id: headOffset
    path: ../Player/Scripts/ControllerConfig.cs
    startLine: 24
  assemblies:
  - Foundry.Core
  namespace: Foundry
  syntax:
    content: public PosRot headOffset
    return:
      type: Foundry.PosRot
    content.vb: Public headOffset As PosRot
- uid: Foundry.ControllerConfig.DeviceOffset.controllerOffsets
  commentId: F:Foundry.ControllerConfig.DeviceOffset.controllerOffsets
  id: controllerOffsets
  parent: Foundry.ControllerConfig.DeviceOffset
  langs:
  - csharp
  - vb
  name: controllerOffsets
  nameWithType: ControllerConfig.DeviceOffset.controllerOffsets
  fullName: Foundry.ControllerConfig.DeviceOffset.controllerOffsets
  type: Field
  source:
    remote:
      path: package/Player/Scripts/ControllerConfig.cs
      branch: main
      repo: https://github.com/FoundryXR/FoundryCore
    id: controllerOffsets
    path: ../Player/Scripts/ControllerConfig.cs
    startLine: 29
  assemblies:
  - Foundry.Core
  namespace: Foundry
  syntax:
    content: public ControllerConfig.ControllerOffset controllerOffsets
    return:
      type: Foundry.ControllerConfig.ControllerOffset
    content.vb: Public controllerOffsets As ControllerConfig.ControllerOffset
references:
- uid: Foundry
  commentId: N:Foundry
  href: Foundry.html
  name: Foundry
  nameWithType: Foundry
  fullName: Foundry
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Foundry.PosRot
  commentId: T:Foundry.PosRot
  parent: Foundry
  href: Foundry.PosRot.html
  name: PosRot
  nameWithType: PosRot
  fullName: Foundry.PosRot
- uid: Foundry.ControllerConfig.ControllerOffset
  commentId: T:Foundry.ControllerConfig.ControllerOffset
  parent: Foundry
  href: Foundry.ControllerConfig.html
  name: ControllerConfig.ControllerOffset
  nameWithType: ControllerConfig.ControllerOffset
  fullName: Foundry.ControllerConfig.ControllerOffset
  spec.csharp:
  - uid: Foundry.ControllerConfig
    name: ControllerConfig
    href: Foundry.ControllerConfig.html
  - name: .
  - uid: Foundry.ControllerConfig.ControllerOffset
    name: ControllerOffset
    href: Foundry.ControllerConfig.ControllerOffset.html
  spec.vb:
  - uid: Foundry.ControllerConfig
    name: ControllerConfig
    href: Foundry.ControllerConfig.html
  - name: .
  - uid: Foundry.ControllerConfig.ControllerOffset
    name: ControllerOffset
    href: Foundry.ControllerConfig.ControllerOffset.html
